language: ruby

services:
  - docker

script:
  - docker build -t "$DOCKER_USERNAME"/zabbix-lamp:1.0 .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push zabbix-lamp:1.0